version: '3'

services:
  web:
    image: "nginx:mainline-alpine"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./deploy/nginx:/etc/nginx/conf.d"
      - "./deploy/ssl:/etc/nginx/ssl"
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 60s
      timeout: 5s
      start_period: 5s
    depends_on:
      - "streamer"
      - "encoder"
      - "phpmyadmin"

  streamer:
    image: "docker.io/avideo/streamer:master"
    # build: .
    restart: "unless-stopped"
    environment:
      SERVER_NAME: "localhost"
      DB_MYSQL_HOST: "database"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "avideo"
      DB_MYSQL_USER: "avideo"
      DB_MYSQL_PASSWORD: "avideo"
      ENABLE_ENCODER: "no"
      ENCODER_URL: "https://localhost/encoder"
      CONTACT_EMAIL: "admin@localhost"
      SYSTEM_ADMIN_PASSWORD: "password"
      WEBSITE_TITLE: "AVideo"
      MAIN_LANGUAGE: "en_US"
    depends_on:
      - database
    networks:
      - app_net

  encoder:
    image: "docker.io/avideo/encoder:master"
    # build: .
    restart: "unless-stopped"
    environment:
      SERVER_NAME: "localhost"
      DB_MYSQL_HOST: "database"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "avideo"
      DB_MYSQL_USER: "avideo"
      DB_MYSQL_PASSWORD: "avideo"
      CONTACT_EMAIL: "admin@localhost"
      STREAMER_URL: "https://localhost/"
      STREAMER_USER: "admin"
      STREAMER_PASSWORD: "password"
    depends_on:
      - database
    networks:
      - app_net

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: "unless-stopped"
    environment:
      PMA_ABSOLUTE_URI: "https://localhost/phpmyadmin"
      PMA_HOST: "database"
      PMA_PORT: 3306
      PMA_CONTROLUSER: "avideo"
      PMA_CONTROLPASS: "avideo"
      PMA_PMADB: "avideo"
      HIDE_PHP_VERSION: "true"
    depends_on:
      - database
    networks:
      - app_net

  database:
    image: "mariadb:latest"
    restart: "unless-stopped"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: "avideo"
      MYSQL_USER: "avideo"
      MYSQL_PASSWORD: "avideo"
    volumes:
      - ./.compose/db:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
